### ISSUE TITLE
--right naming

### ISSUE THREAD

**Issue by csshugs** [csshugs/objects.flex-layout#1]
rethink naming (reverse flex direction)

**Comment by nenadjelovac** [comment]
@csshugs what do you mean by this?

**Comment by csshugs** [comment]
@nenadjelovac When `flex-direction` is `row-reversed`, then "--right" would be wrong naming, because the items would be left aligned and not right.
The Question is, would anyone do this in a global grid? – Reversing the order of all grid-items?

**Comment by nenadjelovac** [comment]
@csshugs I think what you are going after is actually `layout--rev` (which exist in layout already https://github.com/inuitcss/objects.layout/blob/master/_objects.layout.scss#L186). I think you should go with the same naming. Just have in mind that in that case you need to add `direction: ltr` for it to function the same as in `inline-block` implementation.

Having said that, layout reversed is missing in flex-layout, so why not include it? :)

**Comment by csshugs** [comment]
@nenadjelovac 

> I think what you are going after is actually layout--rev

No, actually I'm after [`layout--right`](http://csshugs.github.io/inuit-kitchen-sink/layout.html#-layout-right-) which exists already in inuit and provides a way to align the items in a row, when the row is not filled up entirely with layout-items.

`layout--rev` reverses the actual order of the layout-items, which is not what I want, but that's what happens, when `layout--rev` is combined with `layout--right`. But then `layout--right` produces **left** aligned layout-items because of `layout--rev`. So here the naming fails.

You can test it [here](http://codepen.io/csshugs/pen/OVovvo).

> Having said that, layout reversed is missing in flex-layout, so why not include it? :)

It's not missing, because this module is not intended to replace the original inuit-layout module, but rather enhance it with an opportunity to obtain layout-items which are all the same height in each row ([see here](http://codepen.io/csshugs/pen/OVovvo)). 
That's actually the only reason, why I introduced this plugin. It's not intended to displace the `display: inline-block` layout method. That's why this module just provides a modifier-class rather than overriding the original `.layout` class.

**Comment by csshugs** [comment]
Since I'm not very happy with this repos code at the moment (naming etc.), I'll close this for now and will come back to it, if I'll someday continue working on this idea.
